# Generated by Django 4.0.5 on 2022-07-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='task', to='webapp.type'),
        ),
    ]
