# Generated by Django 4.0.5 on 2022-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='task', to='webapp.type', verbose_name='Тип'),
        ),
    ]
